language: node_js
node_js:
  - "10"
cache: yarn
notifications:
  email: false
env:
  matrix:
    - CHROMATIC: "false"
      JEST_MAX_WORKERS: 4
    - CHROMATIC: "true"

script:
  - if [ "$CHROMATIC" == "false" ]; then  yarn test                         ; fi
#  - if [ "$CHROMATIC" == "true" ];  then  yarn build && yarn build-stories && yarn test-stories   ; fi
